export enum EPermission {
	Ping = "commands.ping",
	ReplaceRole = "commands.replaceRole",
	ChannelClear = "commands.clear",
	roupsCreate = "commands.groups.create",
	GroupsUpdate = "commands.groups.update",
	GroupsDelete = "commands.groups.delete",
	GroupsList = "commands.groups.list",
	TempMute = "commands.tempmute",
	Ban = "commands.ban",
	Unmute = "commands.unmute",
	Unban = "commands.unban",
	Config = "commands.config",
	SyncBackup = "commands.sync.backup",
	SyncRestore = "commands.sync.restore",
	SanctionsList = "commands.sanctions.list",
}
