-- AlterTable
ALTER TABLE `Achievement` MODIFY `type` ENUM('MESSAGE_COUNT', 'VOICE_DURATION', 'INVITE_COUNT', 'MESSAGE_RATE', 'STREAK_DAYS', 'CHANNEL_DIVERSITY', 'REACTION_COUNT', 'STREAM_DURATION', 'WORD_COUNT_AVG', 'MEDIA_COUNT', 'MENTION_REACH', 'COMMAND_USAGE', 'VOICE_PEAK_TIME') NOT NULL;

-- AlterTable
ALTER TABLE `UserStats` ADD COLUMN `commandCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `dailyStreak` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `lastDailyActivity` DATETIME(3) NULL,
    ADD COLUMN `mediaCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `reactionCount` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `streamDuration` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `totalWords` INTEGER NOT NULL DEFAULT 0;
